# Generated by Django 5.1.6 on 2025-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='count',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='code_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_update',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='new_item',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sold_out',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.TextField(default=''),
        ),
    ]
