# Generated by Django 5.1.6 on 2025-03-07 00:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_inventoryitem_count_inventoryitem_buy_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='description',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='buy_price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category_num',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='code_num',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='new_item',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sold_out',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='weight',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_category',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_name', models.TextField(default='')),
                ('stock_count', models.IntegerField(default=0)),
                ('minimum_count', models.IntegerField(default=0)),
                ('brand', models.TextField(default='')),
                ('item_category', models.TextField(default='')),
                ('cost', models.IntegerField(default=0)),
                ('location', models.TextField(default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory item',
                'verbose_name_plural': 'historical inventory items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
