# Generated by Django 5.1.6 on 2025-03-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_description_inventoryitem_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
