# Generated by Django 5.1.6 on 2025-03-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_historicalinventoryitem_donated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinventoryitem',
            old_name='minimum_count',
            new_name='base_count',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='minimum_count',
            new_name='base_count',
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
