# Generated by Django 5.1.6 on 2025-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_minimum_count_historicalinventoryitem_base_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='amount_in_bulk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='bulk_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='bulk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalinventoryitem',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amount_in_bulk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='bulk_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RenameField(
            model_name='historicalinventoryitem',
            old_name='cost',
            new_name="individual_cost",
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='cost',
            new_name="individual_cost",
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name="individual_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='individual_cost',
           field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='bulk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
