# Generated by Django 5.1.6 on 2025-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_historicalinventoryitem_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='bulk_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalinventoryitem',
            name='individual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='bulk_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='individual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
