# Generated by Django 5.1.6 on 2025-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_historicalinventoryitem_bulk_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_category',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_category',
            field=models.ManyToManyField(to='management.itemcategory'),
        ),
    ]
