# Generated by Django 5.1.6 on 2025-04-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_itemcategory_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='historicalinventoryitem',
        #     name='item_category',
        #     field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.itemcategory'),
        # ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_category',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.itemcategory'),
        ),
    ]
